<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-3TR6LPOF" failures="1" tests="4" name="Default test(failed)" time="63.19" errors="0" timestamp="23 Apr 2025 05:20:53 GMT">
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContactWithOrg_Test" time="12.985">
    <skipped/>
  </testcase> <!-- createContactWithOrg_Test -->
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContactWithOrg_Test" time="12.332">
    <skipped/>
  </testcase> <!-- createContactWithOrg_Test -->
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContactWithOrg_Test" time="12.262">
    <skipped/>
  </testcase> <!-- createContactWithOrg_Test -->
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContactWithOrg_Test" time="12.746">
    <failure type="java.lang.AssertionError" message="expected [Das_4599] but found [TY_4654]">
      <![CDATA[java.lang.AssertionError: expected [Das_4599] but found [TY_4654]
at com.comcast.crm.vtigerapplicationtest.Contact_Test.createContactWithOrg_Test(Contact_Test.java:75)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createContactWithOrg_Test -->
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContact_Test" time="0.0">
    <ignored/>
  </testcase> <!-- createContact_Test -->
  <testcase classname="com.comcast.crm.vtigerapplicationtest.Contact_Test" name="createContactWithSupportDate_Test" time="0.0">
    <ignored/>
  </testcase> <!-- createContactWithSupportDate_Test -->
</testsuite> <!-- Default test(failed) -->
